### ISSUE TITLE
Issue building new project with template barebone

### ISSUE THREAD

**Issue by Elrinth** [VUEngine/VUEngine-Studio#62]
The default path suggested by VUEngine Studio is: "C:\Users\VirtualBoy\vuengine\projects" which doesn't exist after installation.
So trying to create a new project it results in:
![image](https://user-images.githubusercontent.com/224418/220202843-561e1525-eedb-4406-99c8-d864c3811c37.png)

Manually creating the folder structure (C:\Users\VirtualBoy\vuengine\projects) solved the issue ofcourse. It would create the last folder (game folder) without any problem by the program.

Oh and btw, yes my computer is called VirtualBoy :D

After the project is created it would be sweet if side panel was automagically opened to show files and maybe the source folder expanded cuz that's usually where one would look. 

Then I just clicked build project, but the cog wheel spins indefinetly at 0%. Should some kind of terminal be shown also?
![image](https://user-images.githubusercontent.com/224418/220203547-6fae0748-e3b0-4aea-9bf7-c6a71e710a1a.png)

Maybe Problems and Output can be default opened aswell?
![image](https://user-images.githubusercontent.com/224418/220203717-c732efeb-a830-4680-be0b-e7119c008b2b.png)

After a long time it showed me build errors (this is simply starting a new project and using the BAREBONE template):
Running pre-build tasks...
No tasks found.
mkdir: cannot change permissions of '/dev/shm': Permission denied
mkdir: cannot change permissions of '/dev/mqueue'
: Permission denied
Copying skeleton files.
These files are for the users to personalise their msys2 experience.

They will never be overwritten nor automatically updated.
'./.bashrc' -> '/home/VirtualBoy/.bashrc'
'./.bash_logout' -> '/home/VirtualBoy/.bash_logout'
'./.bash_profile' -> '/home/VirtualBoy/.bash_profile'
'./.inputrc' -> '/home/VirtualBoy/.inputrc'
'./.profile' -> '/home/VirtualBoy/.profile'
STARTING BUILD
Starting at: Mon Feb 20 22:49:35 CET 2023
Build type:  beta
Compiler:    v810 4.7
Make Jobs:   31
Finding total number of components
Components: 30
(1/30) Preprocessing core
Preprocessed class: Object
Preprocessed class: CameraMovementManager
Preprocessed class: VirtualNode
Preprocessed class: MemoryPool
Preprocessed class: Camera
Preprocessed class: Game
Preprocessed class: Clock
Preprocessed class: VirtualList
Preprocessed class: Size
Preprocessed class: Sprite
Preprocessed class: Printing
Preprocessed class: MessageDispatcher
Preprocessed class: SpriteManager
Preprocessed class: Utilities
Preprocessed class: PixelVector
Preprocessed class: StopwatchManager
Preprocessed class: StateMachine
Preprocessed class: AnimationCoordinatorFactory
Preprocessed class: Stopwatch
Preprocessed class: Optics
Preprocessed class: CameraEffectManager
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: ObjectSpriteContainer
Preprocessed class: Texture
Preprocessed class: State
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: PixelSize
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: BgmapTextureManager
Preprocessed class: AnimationCoordinator
Preprocessed class: Wireframe
Preprocessed class: ParamTableManager
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: BgmapTexture
Preprocessed class: CharSetManager
Preprocessed class: Telegram
Preprocessed class: DirectDraw
Preprocessed class: TimerManager
Preprocessed class: Error
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: BgmapSprite
Preprocessed class: SoundManager
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Affine
Preprocessed class: Vector3D
Preprocessed class: AnimationController
Preprocessed class: ObjectSprite
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: KeypadManager
Preprocessed class: Line
Preprocessed class: RumblePakManager
Preprocessed class: Shape
Preprocessed class: Polyhedron
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: MBgmapSprite
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: ClockManager
Preprocessed class: CharSet
Preprocessed class: CollisionHelper
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: FrameRate
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Sphere
Preprocessed class: CollisionManager
Preprocessed class: PrintingSprite
Preprocessed class: Math
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Ball
Preprocessed class: Mem
Preprocessed class: CommunicationManager
Preprocessed class: SoundWrapper
Preprocessed class: MBgmapAnimatedSprite
Preprocessed class: VIPManager
Preprocessed class: Behavior
Preprocessed class: WireframeManager
Preprocessed class: BgmapAnimatedSprite
Preprocessed class: TextObjectSprite
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: SRAMManager
Preprocessed class: ObjectTexture
Preprocessed class: LineField
Preprocessed class: PhysicalWorld
Preprocessed class: HardwareManager
Preprocessed class: GameState
Preprocessed class: VirtualCircularList
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Body
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: OptionsSelector
Preprocessed class: ToolState
Preprocessed class: EntityFactory
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: ObjectTextureManager
Preprocessed class: ParticleBody
Preprocessed class: Profiler
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: StageEditorState
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: ParticleRemover
Preprocessed class: Tool
Preprocessed class: SoundTestState
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: AnimationInspectorState
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Box
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Optical
Preprocessed class: SpatialObject
Preprocessed class: SoundTest
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: StageEditor
Preprocessed class: ObjectAnimatedSprite
Preprocessed class: DebugState
Stage: base class Container not found
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
make[2]: *** [/c/VUEngine/resources/app/vuengine/vuengine-core/makefile-preprocess:32: /c/Users/VirtualBoy/vuengine/projects/vbdoom/build/beta/objects/core/source/stage/Stage.h] Error 1
make[2]: *** Waiting for unfinished jobs....
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Particle
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Entity: base class Container not found
Preprocessed class: AnimationInspector
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Container
Preprocessed class: Debug
Actor: base class AnimatedEntity not found
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
make[2]: *** [/c/VUEngine/resources/app/vuengine/vuengine-core/makefile-preprocess:32: /c/Users/VirtualBoy/vuengine/projects/vbdoom/build/beta/objects/core/source/stage/entities/Actor.h] Error 1
Preprocessed class: InverseBox
Preprocessed class: PhysicalParticle
/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
ParticleSystem: base class Entity not found
make[2]: *** [/c/VUEngine/resources/app/vuengine/vuengine-core/makefile-preprocess:32: /c/Users/VirtualBoy/vuengine/projects/vbdoom/build/beta/objects/core/source/stage/entities/Particles/ParticleSystem.h] Error 1
Preprocessed class: UIContainer
Preprocessed class: SolidParticle
AnimatedEntity: base class Entity not found
make[2]: *** [/c/VUEngine/resources/app/vuengine/vuengine-core/makefile-preprocess:32: /c/Users/VirtualBoy/vuengine/projects/vbdoom/build/beta/objects/core/source/stage/entities/AnimatedEntity.h] Error 1
make[1]: *** [/c/VUEngine/resources/app/vuengine/vuengine-core/makefile-common:195: preprocessHeaderFiles] Error 2
make: *** [/c/VUEngine/resources/app/vuengine/vuengine-core/makefile-common:136: preprocessEngine] Error 2

**Comment by KR155E** [comment]
Best computer name ever! 🤩

Thanks for your suggestions. The Problems and Output views are of not that much use, so I don't think showing them by default makes sense. But I'll think about auto creating the default folder when the user chooses to use it.

About your building problems:

The preprocessor warnings do no harm and can be safely ignored. They will be fixed in the next release.

msys2 works only semi decently as a build environment for VUEngine, unfortunately. I personally haven't worked with it in a long time but I remember there being occassional random build errors out of nowhere. The same thing seems to have happened for you. Please try to just build again and it should go beyond the point it errored out before. If another error pops up, try yet again. 

I suggest installing WSL1 as a replacement for msys. VUEngine Studio will automatically detect and use it. It should increase stability and will also reduce build times significantly. See: https://www.vuengine.dev/documentation/setup/enhancing-build-times-on-windows/

Please let us know if the above worked for you.

**Comment by Elrinth** [comment]
I installed WSL, it builds much faster :) but not super fast. But it fails:

Running pre-build tasks...
No tasks found.
STARTING BUILD
Starting at: Wed Feb 22 08:49:56 CET 2023
Build type:  beta
Compiler:    v810 4.7
Make Jobs:   31
Finding total number of components
Components: 30
(1/30) Preprocessing core
/mnt/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
/mnt/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Stage
Preprocessed class: Entity
/mnt/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
/mnt/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: ParticleSystem
Preprocessed class: AnimatedEntity
/mnt/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: Actor
Setting up plugin: coreSetupClasses
(2/30) Preprocessing AstonishFont
(3/30) Preprocessing VirtualBoyFont
(4/30) Preprocessing GuiBgmapAnimatedSprite
(5/30) Preprocessing LowPowerEntity
/mnt/c/VUEngine/resources/app/vuengine/vuengine-core/lib/compiler/preprocessor/processHeaderFile.sh: line 430: warning: here-document at line 430 delimited by end-of-file (wanted `$baseBaseClassNameLine')
Preprocessed class: LowPowerEntity
Setting up plugin: LowPowerEntitySetupClasses
(6/30) Preprocessing I18n
(7/30) Preprocessing AutomaticPause
(8/30) Preprocessing SaveDataManager
(9/30) Preprocessing LowPowerIndicator
(10/30) Preprocessing SplashScreen
(11/30) Preprocessing AdjustmentScreenVUEngine
(12/30) Preprocessing AutomaticPauseSelectionScreen
(13/30) Preprocessing LanguageSelectionScreen
(14/30) Preprocessing PrecautionScreen
(15/30) Preprocessing Game
make[1]: *** No rule to make target '/c/VUEngine/resources/app/vuengine/vuengine-plugins//other/SaveDataManager/source/SaveDataManager/SaveDataManager.h', needed by 'build/beta/objects/Game/source/components/GameSaveDataManager.h'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make: *** [/mnt/c/VUEngine/resources/app/vuengine/vuengine-core/makefile-common:195: preprocessHeaderFiles] Error 2

**Comment by Elrinth** [comment]
well now this time it seemed to have built... but the play button does nothing.

ed: preserving permissions for 'build/beta/objects/Game/source/states/HelloWorldScreenState/sedFUh5Jt': Operation not permitted
Compiling asset: languages/Spec/SpanishLanguageSpec.c
sed: preserving permissions for 'build/beta/objects/Game/source/states/HelloWorldScreenState/sedRU21Ib': Operation not permitted
sed: preserving permissions for 'build/beta/objects/Game/source/states/HelloWorldScreenState/sedNVoPPX': Operation not permitted
cp: preserving times for 'build/beta/objects/Game/assets/stages/HelloWorldStageSpec.c': Operation not permitted
Compiling asset: stages/HelloWorldStageSpec.c
Compiling file:  Game/GameSetupClasses.c
Linking game library
Linking build/beta/output-beta.elf...
12K	build/libAdjustmentScreenVUEngine.a
4.0K	build/libAstonishFont.a
8.0K	build/libAutomaticPause.a
24K	build/libAutomaticPauseSelectionScreen.a
36K	build/libGame.a
4.0K	build/libGuiBgmapAnimatedSprite.a
4.0K	build/libI18n.a
24K	build/libLanguageSelectionScreen.a
4.0K	build/libLowPowerEntity.a
4.0K	build/libLowPowerIndicator.a
8.0K	build/libPrecautionScreen.a
12K	build/libSaveDataManager.a
4.0K	build/libSplashScreen.a
4.0K	build/libVirtualBoyFont.a
92K	build/libcore.a
1.0M	build/output.vb
BUILD FINISHED
Done compiling in beta mode with GCC 4.7
Started at: 10:27:06
Ended at:   10:29:45
Total time: 2 min. 39 sec.
Running post-build tasks...
No tasks found.

**Comment by KR155E** [comment]
Progress!

I think the permission errors have to do with the preprocessor and can be ignored. I don't know where they come from. The build seems to have worked after all. 

Now, once the build has finished, the play button should open the built-in emulator and start the freshly build ROM. Can you if it's there in the file explorer at `build/output.vb`? Does the emulator start up when you click the ROM file? If still nothing happens, could you please open up the Developer Tools (Main menu under Help) and see if there's an error in the Console tab?

**Comment by Elrinth** [comment]
there is indeed a output.vb there. I try double click it in workspace, nothing happen.

![image](https://user-images.githubusercontent.com/224418/220615270-b1cad663-64ec-456f-bc15-d243d031af55.png)

**Comment by KR155E** [comment]
That is strange! For some reason, the built-in Retroarch Web errors out. I'll have to debug the problem. 

As a temporary workaround, I suggest configuring VUEngine Studio to use another emulator. See https://www.vuengine.dev/documentation/user-guide/emulator/

Mednafen is recommended: https://forum.fobby.net/index.php?t=rview&goto=6619&th=2057#msg_6619
