### ISSUE TITLE
Can't compile projets on Windows

### ISSUE THREAD

**Issue by ultrasuperpingu** [VUEngine/VUEngine-Studio#77]
I just tried the last version of VU Engine.
I installed it and tried to compiled an old project (0.1 I think). It was just a template with dumb modifications. I had to copy/past the ".theia-workspace" to ".workspace" to open it and the project opened flawlessly. But when trying to build, it returns:

`make: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found (required by make)`

So I tried to create a new project from template (Showcase), and I got the same error.

Did I missed something ?

**Comment by KR155E** [comment]
The error appears to originate in WSL. Please ensure that your WSL installation is up to date and has necessary libs installed as described [here](https://www.vuengine.dev/documentation/setup/enhancing-build-times-on-windows/).

**Comment by ultrasuperpingu** [comment]
Just to know, is it really hard to make it possible to compile with glibc 2.31 (= the last debian)?
