### ISSUE TITLE
Incorrect config.make after removing unused Plugin

### ISSUE THREAD

**Issue by ultrasuperpingu** [VUEngine/VUEngine-Studio#78]
After removing unusued PostProcess plugins, the corresponding plugins were correctly removed from config.make but COMPILER_OUTPUT, OPTIMIZATION and all _SECTION  fields were empty. As a result, the project was not compiling. Filling those fields back resolve the problem.

Edit: It seems that Astonish* declarations are also removed from Font.c and Font.h.
All WaveForms are also removed from WaveForms.h

**Comment by KR155E** [comment]
Does your project contain a CompilerConfig file? Sounds like it doesn't. But in that case, a default compiler config from VUEngine-Core should be used. Do you have a custom engine path set (build.engine.core.path)?

**Comment by ultrasuperpingu** [comment]
The project was created with the new project wizard with the template Showcase.

It seems I have a CompilerConfig:
`{
    "framePointer": false,
    "memorySections": {
        "dram": {
            "length": -19,
            "origin": "0x0003D800"
        },
        "exp": {
            "length": 16,
            "origin": "0x04000000"
        },
        "rom": {
            "length": 16,
            "origin": "0x07000000"
        },
        "sram": {
            "length": 16,
            "origin": "0x06000000"
        },
        "wram": {
            "length": 64,
            "origin": "0x05000000"
        }
    },
    "memoryUsage": {
        "initializedData": ".sdata",
        "memoryPool": ".sdata",
        "staticSingletons": ".dram_bss",
        "uninitializedData": ".sbss",
        "virtualTables": ".dram_bss"
    },
    "optimization": "O2",
    "output": "c",
    "prologFunctions": false
}`

No build.engine.core.path is set indeed.

Thanks for your help
